// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9LVb-uJTZ1BF5rWbynCznQ15iI9TFc4Q',
    appId: '1:56953654132:web:aef567381f97771e827a21',
    messagingSenderId: '56953654132',
    projectId: 'financas-e8c3c',
    authDomain: 'financas-e8c3c.firebaseapp.com',
    storageBucket: 'financas-e8c3c.appspot.com',
    measurementId: 'G-1P9LEDNNWE',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9LVb-uJTZ1BF5rWbynCznQ15iI9TFc4Q',
    appId: '1:56953654132:web:354764e7bd6ceae9827a21',
    messagingSenderId: '56953654132',
    projectId: 'financas-e8c3c',
    authDomain: 'financas-e8c3c.firebaseapp.com',
    storageBucket: 'financas-e8c3c.appspot.com',
    measurementId: 'G-NRFEKVPBY3',
  );
}
